<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }

            #containerLiens {
                width: 500px;
                margin: 40px auto 0px auto;
            }

            a {
                display: block;
                padding: 5px 10px;
                margin-bottom: 20px;
                text-decoration: none;
                border: 1px solid lightgrey;
                color: lightgrey;
            }
            
            a:hover {
                color: white;       
                background-color: lightgrey;         
            }
        </style>
    </head>
    <body>
        <h1>Slim</h1>
        <div>A microframework for PHP</div>

        <div id="containerLiens">
            <a href="allwines">Voir la liste des vins</a>
            <a href="pictureswines">Voir tous les vins accompagnés de leur photo</a>
            <a href="countrieswines">Voir la liste des vins triée par pays</a>
        </div>
    </body>
</html>
